apiVersion: apps/v1
kind: Deployment
metadata:
  name: codif-ape-graph-rag-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codif-ape-graph-rag-streamlit
  template:
    metadata:
      labels:
        app: codif-ape-graph-rag-streamlit
    spec:
      containers:
        - name: streamlit
          image: meilametayebjee/codification-ape-graph-rag-api:cd
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: NEO4J_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neo4j
                  key: apiKey
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "100m"
              memory: "512Mi"
