apiVersion: v1
kind: Service
metadata:
  name: codif-ape-graph-rag-streamlit-service
spec:
  selector:
    app: codif-ape-graph-rag-streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501