FROM inseefrlab/onyxia-vscode-python:py3.12.9

# copy the code in streamlit/
ADD . /streamlit

# Set working directory
WORKDIR /streamlit

# Sync dependencies
RUN uv sync --locked

# Expose port 8501
EXPOSE 8501

# Set working directory to run streamlit
WORKDIR /streamlit/src

CMD ["uv", "run", "streamlit", "run", "streamlit/main.py"]
