FROM inseefrlab/onyxia-vscode-python:py3.12.9

ENV TIMEOUT=3600

# Set working directory
WORKDIR /app

# copy the code in api/
ADD . /app

# Sync dependencies
RUN uv sync --locked

# Expose port 5000
EXPOSE 5000

# Set working directory to run api
WORKDIR /app/src

CMD ["uv", "run", "uvicorn", "api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "5000", "--timeout-graceful-shutdown", "3600"]
