name: Build Images

on:
  push:
    branches:
      - main
      - test-double-images
    tags:
      - "*"
    paths:
      - pyproject.toml
  workflow_dispatch:

jobs:
  image-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfiles/Dockerfile-streamlit
            image: meilametayebjee/codification-ape-graph-rag-streamlit
          - dockerfile: ./Dockerfiles/Dockerfile-api
            image: meilametayebjee/codification-ape-graph-rag-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_USERNAME=${{ secrets.API_USERNAME }}
            API_PASSWORD=${{ secrets.API_PASSWORD }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
